### ISSUE TITLE
utility: no-border

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/minimalist#82]
For elements such as a `fieldset`, it is sometimes preferable to hide the default borders. Turning them off by default for `fieldset` is probably not the way to go so, I propose adding a simple utility class as follows:

```css
.no-border {
  border: 0;
}
```
