### ISSUE TITLE
enhance: buttons

### ISSUE THREAD

**Issue by schalkneethling** [schalkneethling/minimalist#83]
Remove the current `active` state styling as presents problems when more than one button is used together. This is very often the case for example with forms where there is a reset and submit button.

This is the code to remove.

```css
&:active {
    margin-block-start: var(--size-1);
    margin-inline-start: var(--size-1);
  }
```

There can perhaps be something a bit more subtle and less disruptive.
